version: 2.1
executors:
  linux-arm64:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: arm.medium
    working_directory: /home/circleci/go/src/github.com/fergusstrange/embedded-postgres

jobs:
  platform_test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - embedded-postgres-{{ checksum "/home/circleci/go/src/github.com/fergusstrange/embedded-postgres/go.mod" }}
      - run: cd platform-test && go test -v -race ./...
      - save_cache:
          key: embedded-postgres-{{ checksum "/home/circleci/go/src/github.com/fergusstrange/embedded-postgres/go.mod" }}
          paths:
            - /home/circleci/go/pkg

workflows:
  version: 2
  test:
    jobs:
      - platform_test:
          matrix:
            parameters:
              executor: [ linux-arm64 ]
