version: 2.1
executors:
  linux-arm64:
    machine:
      image: ubuntu-2204:2024.01.2
    resource_class: arm.medium
    working_directory: /home/circleci/go/src/github.com/fergusstrange/embedded-postgres
  apple-m4: &macos-executor
    resource_class: m4pro.medium
    macos:
      xcode: "26.1.0"
orbs:
  go: circleci/go@3.0.3
jobs:
  platform_test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - when:
          condition:
            equal: [ *macos-executor, << parameters.executor >> ]
          steps:
            - go/install
      - go/load-mod-cache
      - go/mod-download
      - go/save-mod-cache
      - run: cd platform-test && go mod download && go test -v -race ./...

workflows:
  version: 2
  test:
    jobs:
      - platform_test:
          matrix:
            parameters:
              executor:
                - linux-arm64
                - apple-m2
